server:
  port: 8080

spring:
  application:
    name: abhayecom

  data:
    mongodb:
      uri: mongodb+srv://abhay24bcs:ecom12345@cluster0.80audxg.mongodb.net/ecommerce?retryWrites=true&w=majority
